http:
  probing:
    timeout: "10s"
    max_redirects: 5
    concurrency: 20
    protocols:
      - "https"
      - "http"

  evasion:
    user_agents:
      - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
      - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
      - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    rotate_user_agent: true
    use_proxies: true
    proxy_rotation_interval: "1m"

  redirects:
    max_redirects: 10
    max_depth: 5
    follow_same_host: true
    follow_cross_host: false
    timeout: "15s"

  playwright:
    timeout: "30s"
    headless: true
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    viewport_width: 1920
    viewport_height: 1080

  analysis:
    similarity_threshold: 0.85
    check_dead_pages: true
    check_error_pages: true
    check_security_headers: true
    check_server_technology: true

  logging:
    level: "info"
    log_failures: true
    log_successes: false
    log_redirects: true