wordlists:
  directory: "./configs/wordlists"
  auto_reload: true
  reload_interval: "5m"

generation:
  max_concurrent: 100
  max_depth: 3
  max_permutations: 1000000
  use_common_wordlists: true
  use_combinatorics: true
  use_fuzzing: true
  default_industry: ""

markov:
  min_length: 3
  max_length: 15
  training_data_size: 10000

patterns:
  common_separators: ["-", "_", "."]
  numeric_patterns: ["0", "1", "2", "00", "01", "02", "001", "002"]
  environment_prefixes: ["dev", "test", "stage", "prod", "uat", "qa", "preprod"]
  service_suffixes: ["api", "web", "app", "admin", "login", "secure", "internal", "external"]